### ISSUE TITLE
JsonMappingException: Can not deserialize instance of java.util.ArrayList out of VALUE_STRING token

### ISSUE THREAD

**Issue by joe96814** [aws/aws-cloudtrail-processing-library#4]
I have been working on getting CloudTrail setup so that there is a central account where an S3 bucket lies for the CloudTrail logs to be written to and a central SQS queue subscribed to SQS Topics in other accounts.  This setup has been working successfully with the exception of some messages resulting in a JsonMappingException.  The exact messages it:

'''
JsonMappingException: Can not deserialize instance of java.util.ArrayList out of VALUE_STRING token
'''

This exception is occurring in the library when attempting to parse the SQS Message to determine its source.  I reviewed one of the messages and found that the s3ObjectKey value is in fact a String rather than a List, which explains the exception.  The library should support s3ObjectKeys being Strings if sqsMessages generates Strings for the value.  The message itself does not appear to be a CloudTrail message but it would seem that the library should support parsing the messages successfully, and reject based on the fact that its not a cloud trail message, or give the user of the library the ability to reject the message.

Below is the relevant parts an example message causing the issue:

'''
"Type" : "Notification",
  "MessageId" : "<obfuscated>",
  "TopicArn" : "arn:aws:sns:us-west-2:222222222222:MyTopic",
  "Subject" : "[AWS Config:us-west-2] Configuration History Delivery Completed for Account 222222222222",
  "Message" : "{\"s3ObjectKey\":\"us-west-2/AWSLogs/222222222222/Config/us-west-2/2015/11/17/ConfigHistory/222222222222_Config_us-west-2_ConfigHistory_AWS::EC2::Subnet_20151117T164715Z_20151117T222216Z_1.json.gz\",\"s3Bucket\":\"MyBucket\",\"notificationCreationTime\":\"2015-11-17T22:38:57.729Z\",\"messageType\":\"ConfigurationHistoryDeliveryCompleted\",\"recordVersion\":\"1.1\"}",
  "Timestamp" : "2015-11-17T22:38:57.744Z",
'''

**Comment by curtca** [comment]
Thank you for reporting this. This is a bug. But honestly, even the "fix" is probably just throwing a different exception. Conceptually, it doesn't make sense to put non-CloudTrail messages into the queue. CPL wouldn't know what to do with them, hence it would throw an exception. Granted, it could throw a better exception.

In the meantime, I highly recommend that you do not choose the same SQS queue for both CloudTrail and Config messages. They're just different producers and different consumers. It's like mixing 110v and 220v electricity in order to handle both types of devices. It doesn't work very well.

Cheers,

Curt
