### ISSUE TITLE
Application not polling from SQS Queue

### ISSUE THREAD

**Issue by michaelqiu94** [aws/aws-cloudtrail-processing-library#5]
Hi,  
   I tried to run the sample application, SampleApp. However, it constantly returns: 
pollQueue is false , and latency is 202832 milliseconds.
   This seems to be from the SampleProgressReporter, and the executor never seems to go past the pollQueue phase. Any ideas on how to fix this? Thanks.

Best,
Michael Qiu

**Comment by simongjh** [comment]
Hi Mike

Thanks for bring this issue up. From the logs, the polling queue operation took longer than 20 seconds, which most likely reached the long pulling time limit. Before we dive deep, I would like to collect a few pieces of information from you:

1. Is this issue still happening? Did you try to restart your application?
2. Is this just happened today? Or it worked fine, and just stopped working?
3. Do you have the queue setup correctly? Can you double check the permission of the queue, make sure the queue is in the right region as you configured and has correct permission to allow your application to pull messages.
4. Is there any CloudTrail notification messages in the queue? If not, can you wait and generate a few CloudTrail notifications by invoke some AWS APIs? 
5. Lastly, any other error message you saw in your application log?

Appreciate if you could double check above mentioned cases, and with those additional information, we could help to identify the root cause. 

Thanks again to use this library and report issue.

- Simon

**Comment by michaelqiu94** [comment]
Hi Simon
     Thanks for the reply. 

1. The issue is still happening, even if I restart the application.
2. I ran it for the first time yesterday and it didn't work. I tried again today, and same result.
3. I have a queue on SQS set up, and it is in us-east-1, as I have configured in my cloudtrail properties file. 
4. I have my queue subscribed to an SNS topic, and this one generates messages pretty frequently (once every minute or 2). 
5. I don't see any other error messages besides this log4j warning:
log4j:WARN No appenders could be found for logger (com.amazonaws.services.cloudtrail.processinglibrary.AWSCloudTrailProcessingExecutor).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Thanks!
Best,
Michael

**Comment by simongjh** [comment]
Based on the error message, seems related to the timeout (socket and connection) setting in the SQS client. Did you pass in your own SQS client or use the default SQS client? If you pass in your own SQS client, can you let me know your timeout setting?

**Comment by michaelqiu94** [comment]
I used the default SQS client.

**Comment by mingma7** [comment]
Hi Mike,
 
I wonder if this issue is still happening. If so, feel free to reopen the issue.
 
For your reference, I ran the sample application from scratch in the following steps:
1. Update the awscloudtrailprocessinglibrary.properties with at least following changes:
    1. accessKey
    2. secretKey
    3. sqsUrl
    4. sqsRegion
2. Could you verify your accessKey and secretKey are matched, active and have rights to access the SQS queue you configured above?
3. Could you verify your sqs is subscribed to the right SNS Topic? (Easy way to verify: does your queue have messages coming?)

If all of above steps are configured correct, you are expected to see the following message:

`INFO: pollQueue is true , and latency is 288 milliseconds.`
`Oct 10, 2017 1:40:30 PM sample.SampleProgressReporter reportEnd`
`INFO: parseMessage is true , and latency is 1 milliseconds.`

Please feel free let us know if you have any question. 
 
-Ming
